# Generated by Django 5.2.9 on 2025-12-18 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(blank=True, max_length=500)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('duration', models.PositiveIntegerField()),
                ('provider', models.CharField(choices=[('local', 'Local'), ('s3', 'AWS S3'), ('vimeo', 'Vimeo'), ('youtube', 'YouTube')], default='local', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='lessons.lesson')),
            ],
        ),
    ]
