"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

import os
from pathlib import Path
import sys
import dj_database_url


# Build paths inside the project like: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent




# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'dev-secret-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', '1') == '1'

#In prod is working
ALLOWED_HOSTS = os.environ.get(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1,ignite-api-689743353539.europe-west1.run.app"
).split(",")

#Local test
#---------------------------------
# ENV = os.environ.get("ENV", "local")

# if ENV == "local":
#     ALLOWED_HOSTS = ["localhost", "127.0.0.1", "0.0.0.0"]
# else:
#     raw_hosts = os.environ.get("ALLOWED_HOSTS", "")
#     ALLOWED_HOSTS = [h.strip() for h in raw_hosts.split(",") if h.strip()]

#-----------------------------------

#En local ça ne fonction pas mais en production oui


#Environment
ENV = os.getenv("ENV", "production")

# Allowed hosts
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "*").split(",")

# Cloud Run proxy / HTTPS
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# stockage de données dans le cloud ou en local

USE_CLOUD_STORAGE = os.getenv("USE_CLOUD_STORAGE", "false") == "true"

if USE_CLOUD_STORAGE:
    DEFAULT_FILE_STORAGE = "storages.backends.gcloud.GoogleCloudStorage"
    GS_BUCKET_NAME = os.getenv("GS_BUCKET_NAME")
    GS_DEFAULT_ACL = None
    GS_QUERYSTRING_AUTH = False
    MEDIA_URL = f"https://storage.googleapis.com/{GS_BUCKET_NAME}/"
else:
    DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR / "media"


STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"


# Isoler les fichiers

if "test" in sys.argv:
    MEDIA_ROOT = BASE_DIR / "test_media"

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Stockage
    'storages',

    # Local apps
    'drf_spectacular',
    'corsheaders',
    'core',
    'users',
    'roles',
    'instructors',
    'rest_framework',
    'categories',
    'subcategories',
    'courses',
    'modules',
    'lessons',
    'outcomes',
    'highlights',
    'reviews',
    'carts',
    'cartitems',
    'checkouts',
    'paymentmethods',
    'payments',
    'inscriptions',
    'videos',
    'typequizs',
    'typequestions',
    'typeresponses',
    'quizs',
    'quizquestions',
    'quizoptions',
    'quizattempts',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'

# Database

DATABASE_URL = os.environ.get("DATABASE_URL")


if DATABASE_URL:
    DATABASES = {
    "default": dj_database_url.parse(
    DATABASE_URL,
    conn_max_age=600,
    ssl_require=False,
    )
    }
else:
# Fallback DEV / Docker local uniquement
    DATABASES = {
    "default": {
    "ENGINE": "django.db.backends.postgresql",
    "HOST": os.environ.get("DB_HOST", "localhost"),
    "NAME": os.environ.get("DB_NAME", "app"),
    "USER": os.environ.get("DB_USER", "postgres"),
    "PASSWORD": os.environ.get("DB_PASS", ""),
    "PORT": os.environ.get("DB_PORT", "5432"),
    }
    }
# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'UserAttributeSimilarityValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'MinimumLengthValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'CommonPasswordValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'NumericPasswordValidator'
        ),
    },
]



# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    )
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CORS_ALLOW_CREDENTIALS = True

