# Generated by Django 5.2.11 on 2026-02-18 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_remove_course_requirements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLearningPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_points', to='courses.course')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
