# Generated by Django 5.2.11 on 2026-02-18 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(help_text="Maitriser les bases de l'html/css", max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements_list', to='courses.course')),
            ],
            options={
                'verbose_name': 'Prérequis du cours',
                'verbose_name_plural': 'Prérequis des cours',
                'ordering': ['position'],
            },
        ),
    ]
