# Generated by Django 5.2.10 on 2026-01-14 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizquestions', '0001_initial'),
        ('typeresponses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('quiz_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='quizquestions.quizquestion')),
                ('type_response', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='response', to='typeresponses.typeresponse')),
            ],
            options={
                'verbose_name': 'Quiz Option',
                'verbose_name_plural': 'Quiz Options',
            },
        ),
    ]
