# Generated by Django 5.2.11 on 2026-02-18 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizoptions', '0001_initial'),
        ('quizquestions', '0001_initial'),
        ('typeresponses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizoption',
            name='quiz_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quizquestions.quizquestion'),
        ),
        migrations.AlterField(
            model_name='quizoption',
            name='type_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quiz_options', to='typeresponses.typeresponse'),
        ),
    ]
