# Generated by Django 5.2.10 on 2026-01-13 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizs', '0001_initial'),
        ('typequestions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('points', models.PositiveBigIntegerField(default=1)),
                ('order', models.PositiveIntegerField(help_text="Ordre d'affichage dans le quiz")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='quizs.quiz')),
                ('type_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typequestion', to='typequestions.typequestion')),
            ],
            options={
                'verbose_name': 'Quiz Question',
                'verbose_name_plural': 'Quiz Questions',
                'ordering': ['order'],
                'unique_together': {('quiz', 'order')},
            },
        ),
    ]
