# Generated by Django 5.2.10 on 2026-01-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartitems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
